import { Job } from "./types";

export const JOBS: Job[] = [
  {
    id: "1",
    slug: "mathematics-ai-trainer",
    title: "Mathematics AI Trainer",
    category: "Mathematics",
    categoryColor: "violet",
    payRange: "$25–$45/hr",
    payMin: 25,
    payMax: 45,
    contractType: "Contract",
    location: "Remote · Worldwide",
    tags: ["Calculus", "Linear Algebra", "Statistics", "Problem Solving"],
    description:
      "Evaluate and improve AI-generated math solutions across advanced topics including calculus, linear algebra, and statistics. Help train next-generation math reasoning models.",
    skills: ["Advanced Mathematics", "Critical Thinking", "Technical Writing"],
    duration: "Ongoing",
    level: "Advanced",
    courseId: "c1",
    courseName: "Advanced AI Math Evaluation Program",
  },
  {
    id: "2",
    slug: "coding-expert-ai-trainer",
    title: "Coding Expert AI Trainer",
    category: "Software Engineering",
    categoryColor: "cyan",
    payRange: "$30–$60/hr",
    payMin: 30,
    payMax: 60,
    contractType: "Contract",
    location: "Remote · Worldwide",
    tags: ["Python", "JavaScript", "Code Review", "Algorithms"],
    description:
      "Review and rate AI-generated code, write complex coding challenges, and help train AI coding assistants. Must be proficient in at least two programming languages.",
    skills: ["Programming", "Algorithms", "Data Structures", "Code Review"],
    duration: "Ongoing",
    level: "Senior",
    courseId: "c2",
    courseName: "AI Coding Specialist Program",
  },
  {
    id: "3",
    slug: "cybersecurity-ai-trainer",
    title: "Cybersecurity AI Trainer",
    category: "Cybersecurity",
    categoryColor: "green",
    payRange: "$35–$65/hr",
    payMin: 35,
    payMax: 65,
    contractType: "Contract",
    location: "Remote · Worldwide",
    tags: ["Penetration Testing", "Network Security", "Threat Analysis", "SIEM"],
    description:
      "Train AI systems on cybersecurity concepts, threat detection, and security protocols. Review AI responses for security accuracy and help build safer AI systems.",
    skills: ["Network Security", "Ethical Hacking", "Security Auditing", "Risk Assessment"],
    duration: "Ongoing",
    level: "Expert",
    courseId: "c3",
    courseName: "Cybersecurity AI Certification",
  },
  {
    id: "4",
    slug: "medical-ai-data-annotator",
    title: "Medical AI Data Annotator",
    category: "Healthcare",
    categoryColor: "pink",
    payRange: "$28–$50/hr",
    payMin: 28,
    payMax: 50,
    contractType: "Contract",
    location: "Remote · Worldwide",
    tags: ["Medical Terminology", "Clinical Data", "HIPAA", "Healthcare AI"],
    description:
      "Annotate medical datasets, review AI-generated clinical summaries, and help train healthcare AI models. Medical background required.",
    skills: ["Medical Knowledge", "Data Annotation", "Clinical Documentation", "Attention to Detail"],
    duration: "Ongoing",
    level: "Intermediate",
    courseId: "c4",
    courseName: "Healthcare AI Specialist Certification",
  },
  {
    id: "5",
    slug: "legal-ai-content-reviewer",
    title: "Legal AI Content Reviewer",
    category: "Legal",
    categoryColor: "orange",
    payRange: "$30–$55/hr",
    payMin: 30,
    payMax: 55,
    contractType: "Contract",
    location: "Remote · Worldwide",
    tags: ["Legal Research", "Contract Analysis", "Compliance", "Case Law"],
    description:
      "Review AI-generated legal documents and analyses for accuracy, compliance, and legal soundness. Law degree or paralegal experience required.",
    skills: ["Legal Research", "Contract Law", "Regulatory Compliance", "Legal Writing"],
    duration: "Ongoing",
    level: "Advanced",
    courseId: "c5",
    courseName: "Legal AI Specialist Program",
  },
  {
    id: "6",
    slug: "stem-research-ai-trainer",
    title: "STEM Research AI Trainer",
    category: "Research",
    categoryColor: "blue",
    payRange: "$32–$58/hr",
    payMin: 32,
    payMax: 58,
    contractType: "Contract",
    location: "Remote · Worldwide",
    tags: ["Physics", "Chemistry", "Biology", "Research Papers"],
    description:
      "Help train AI research assistants by reviewing scientific content, fact-checking AI outputs, and curating high-quality STEM training data.",
    skills: ["Scientific Research", "Academic Writing", "Fact-Checking", "Domain Expertise"],
    duration: "Ongoing",
    level: "Advanced",
    courseId: "c6",
    courseName: "STEM AI Research Certification",
  },
  {
    id: "7",
    slug: "creative-writing-ai-trainer",
    title: "Creative Writing AI Trainer",
    category: "Creative",
    categoryColor: "pink",
    payRange: "$18–$35/hr",
    payMin: 18,
    payMax: 35,
    contractType: "Contract",
    location: "Remote · Worldwide",
    tags: ["Storytelling", "Narrative", "Editing", "Creative Direction"],
    description:
      "Rate and improve AI-generated creative content including stories, poetry, scripts, and marketing copy. Help teach AI systems about tone, voice, and creativity.",
    skills: ["Creative Writing", "Editing", "Narrative Structure", "Style Analysis"],
    duration: "Ongoing",
    level: "Intermediate",
    courseId: "c7",
    courseName: "Creative AI Writing Specialist",
  },
  {
    id: "8",
    slug: "financial-ai-analyst-trainer",
    title: "Financial AI Analyst Trainer",
    category: "Finance",
    categoryColor: "green",
    payRange: "$35–$70/hr",
    payMin: 35,
    payMax: 70,
    contractType: "Contract",
    location: "Remote · Worldwide",
    tags: ["Financial Modeling", "Investment Analysis", "Risk Assessment", "Quant"],
    description:
      "Train financial AI models by reviewing analyses, creating benchmark datasets, and evaluating AI-generated financial reports and investment recommendations.",
    skills: ["Financial Analysis", "Quantitative Modeling", "Risk Management", "Excel/Python"],
    duration: "Ongoing",
    level: "Expert",
    courseId: "c8",
    courseName: "Financial AI Specialist Certification",
  },
  {
    id: "9",
    slug: "multilingual-ai-trainer",
    title: "Multilingual AI Trainer",
    category: "Language",
    categoryColor: "cyan",
    payRange: "$20–$40/hr",
    payMin: 20,
    payMax: 40,
    contractType: "Contract",
    location: "Remote · Worldwide",
    tags: ["Translation", "Localization", "NLP", "Linguistics"],
    description:
      "Help train multilingual AI models by providing translations, evaluating language quality, and creating culturally accurate training datasets.",
    skills: ["Bilingual Proficiency", "Translation", "Cultural Knowledge", "Linguistics"],
    duration: "Ongoing",
    level: "Intermediate",
    courseId: "c9",
    courseName: "Multilingual AI Trainer Certification",
  },
  {
    id: "10",
    slug: "image-annotation-specialist",
    title: "Image Annotation Specialist",
    category: "Computer Vision",
    categoryColor: "orange",
    payRange: "$15–$30/hr",
    payMin: 15,
    payMax: 30,
    contractType: "Contract",
    location: "Remote · Worldwide",
    tags: ["Bounding Boxes", "Semantic Segmentation", "Object Detection", "YOLO"],
    description:
      "Annotate images with bounding boxes, segmentation masks, and labels to train computer vision AI models for autonomous systems and robotics.",
    skills: ["Attention to Detail", "Computer Vision Basics", "Annotation Tools", "Quality Control"],
    duration: "Ongoing",
    level: "Beginner",
    courseId: "c10",
    courseName: "Computer Vision AI Annotation Program",
  },
  {
    id: "11",
    slug: "ai-response-quality-reviewer",
    title: "AI Response Quality Reviewer",
    category: "Quality Assurance",
    categoryColor: "violet",
    payRange: "$18–$38/hr",
    payMin: 18,
    payMax: 38,
    contractType: "Contract",
    location: "Remote · Worldwide",
    tags: ["RLHF", "Evaluation", "Ranking", "Feedback"],
    description:
      "Evaluate AI-generated responses for quality, factuality, helpfulness, and safety. Provide detailed feedback to improve large language model outputs.",
    skills: ["Critical Thinking", "Written Communication", "AI Literacy", "Attention to Detail"],
    duration: "Ongoing",
    level: "Intermediate",
    courseId: "c11",
    courseName: "AI Quality Evaluation Specialist",
  },
  {
    id: "12",
    slug: "audio-speech-ai-trainer",
    title: "Audio & Speech AI Trainer",
    category: "Audio",
    categoryColor: "blue",
    payRange: "$20–$42/hr",
    payMin: 20,
    payMax: 42,
    contractType: "Contract",
    location: "Remote · Worldwide",
    tags: ["Speech Recognition", "Audio Labeling", "Transcription", "TTS"],
    description:
      "Record speech samples, transcribe audio, and evaluate speech recognition AI outputs to improve voice AI systems and assistive technologies.",
    skills: ["Clear Diction", "Audio Tools", "Transcription", "Quality Assessment"],
    duration: "Ongoing",
    level: "Beginner",
    courseId: "c12",
    courseName: "Speech AI Trainer Certification",
  },
];

export const CATEGORIES = [
  "All Jobs",
  "Mathematics",
  "Software Engineering",
  "Cybersecurity",
  "Healthcare",
  "Legal",
  "Research",
  "Creative",
  "Finance",
  "Language",
  "Computer Vision",
  "Quality Assurance",
  "Audio",
];